### ISSUE TITLE
AI Amborella Can't understand what need a mine a ore

### ISSUE THREAD

**Issue by mishaash** [Haznobrain/Erekir-liquefied#1]
Unit Amborella (And branch this unit) Can mine a ore, Example: Beprill, If take he under control. But he AI Cant understand what need mine a ore. Please, Fix he AI

https://github.com/user-attachments/assets/1500901e-4249-4826-91a8-74aa613cb7a8

**Comment by Haznobrain** [comment]
I cannot fix this issue because it'd require coding a completly custom ai, wich i do not know to do. Also this is a json mod, so i just can't do it.
I could add a sort of logic processor or some shit just so people stop annoying me with this and can use them to mine stuff.
